# Generated by Django 4.2.4 on 2023-09-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBar', '0004_alter_cliente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='Inventario',
        ),
    ]
